/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolygame;

/**
 *
 * @author Avery Fowler
 */
public class Player3ManagePage extends javax.swing.JDialog {

    /**
     * Creates new form Player1ManagePage
     */
    public Player3ManagePage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        brown1Label = new javax.swing.JLabel();
        brown2Label = new javax.swing.JLabel();
        lightBlueLabel1 = new javax.swing.JLabel();
        lightBlueLabel2 = new javax.swing.JLabel();
        lightBlueLabel3 = new javax.swing.JLabel();
        pinkLabel1 = new javax.swing.JLabel();
        pinkLabel2 = new javax.swing.JLabel();
        pinkLabel3 = new javax.swing.JLabel();
        orangeLabel2 = new javax.swing.JLabel();
        orangeLabel3 = new javax.swing.JLabel();
        orangeLabel1 = new javax.swing.JLabel();
        redLabel1 = new javax.swing.JLabel();
        redLabel2 = new javax.swing.JLabel();
        redLabel3 = new javax.swing.JLabel();
        yellowLabel1 = new javax.swing.JLabel();
        yellowLabel2 = new javax.swing.JLabel();
        yellowLabel3 = new javax.swing.JLabel();
        greenLabel2 = new javax.swing.JLabel();
        greenLabel3 = new javax.swing.JLabel();
        greenLabel1 = new javax.swing.JLabel();
        blueLabel1 = new javax.swing.JLabel();
        blueLabel2 = new javax.swing.JLabel();
        railroadLabel1 = new javax.swing.JLabel();
        railroadLabel2 = new javax.swing.JLabel();
        railroadLabel3 = new javax.swing.JLabel();
        railroadLabel4 = new javax.swing.JLabel();
        railroadLabel5 = new javax.swing.JLabel();
        railroadLabel6 = new javax.swing.JLabel();
        houseFieldBrown1 = new javax.swing.JTextField();
        houseFieldBrown2 = new javax.swing.JTextField();
        houseFieldLightBlue1 = new javax.swing.JTextField();
        houseFieldLightBlue2 = new javax.swing.JTextField();
        houseFieldLightBlue3 = new javax.swing.JTextField();
        houseFieldPink1 = new javax.swing.JTextField();
        houseFieldPink2 = new javax.swing.JTextField();
        houseFieldPink3 = new javax.swing.JTextField();
        houseFieldOrange1 = new javax.swing.JTextField();
        houseFieldOrange2 = new javax.swing.JTextField();
        houseFieldOrange3 = new javax.swing.JTextField();
        houseFieldRed1 = new javax.swing.JTextField();
        houseFieldRed2 = new javax.swing.JTextField();
        houseFieldRed3 = new javax.swing.JTextField();
        houseFieldYellow1 = new javax.swing.JTextField();
        houseFieldYellow2 = new javax.swing.JTextField();
        houseFieldYellow3 = new javax.swing.JTextField();
        houseFieldGreen1 = new javax.swing.JTextField();
        houseFieldGreen2 = new javax.swing.JTextField();
        houseFieldGreen3 = new javax.swing.JTextField();
        houseFieldBlue1 = new javax.swing.JTextField();
        houseFieldBlue2 = new javax.swing.JTextField();
        buyHouseBrown1 = new javax.swing.JButton();
        buyHouseBrown2 = new javax.swing.JButton();
        buyHouseLightBlue1 = new javax.swing.JButton();
        buyHouseLightBlue2 = new javax.swing.JButton();
        buyHouseLightBlue3 = new javax.swing.JButton();
        buyHousePink1 = new javax.swing.JButton();
        buyHousePink2 = new javax.swing.JButton();
        buyHousePink3 = new javax.swing.JButton();
        buyHouseOrange1 = new javax.swing.JButton();
        buyHouseOrange2 = new javax.swing.JButton();
        buyHouseOrange3 = new javax.swing.JButton();
        buyHouseRed1 = new javax.swing.JButton();
        buyHouseRed2 = new javax.swing.JButton();
        buyHouseRed3 = new javax.swing.JButton();
        buyHouseYellow1 = new javax.swing.JButton();
        buyHouseYellow2 = new javax.swing.JButton();
        buyHouseYellow3 = new javax.swing.JButton();
        buyHouseGreen1 = new javax.swing.JButton();
        buyHouseGreen2 = new javax.swing.JButton();
        buyHouseGreen3 = new javax.swing.JButton();
        buyHouseBlue1 = new javax.swing.JButton();
        buyHouseBlue2 = new javax.swing.JButton();
        sellHouseBrown1 = new javax.swing.JButton();
        sellHouseBrown2 = new javax.swing.JButton();
        sellHouseLightBlue1 = new javax.swing.JButton();
        sellHouseLightBlue2 = new javax.swing.JButton();
        sellHouseLightBlue3 = new javax.swing.JButton();
        sellHousePink1 = new javax.swing.JButton();
        sellHousePink2 = new javax.swing.JButton();
        sellHousePink3 = new javax.swing.JButton();
        sellHouseOrange1 = new javax.swing.JButton();
        sellHouseOrange2 = new javax.swing.JButton();
        sellHouseOrange3 = new javax.swing.JButton();
        sellHouseRed1 = new javax.swing.JButton();
        sellHouseRed2 = new javax.swing.JButton();
        sellHouseRed3 = new javax.swing.JButton();
        sellHouseYellow1 = new javax.swing.JButton();
        sellHouseYellow2 = new javax.swing.JButton();
        sellHouseYellow3 = new javax.swing.JButton();
        sellHouseGreen1 = new javax.swing.JButton();
        sellHouseGreen2 = new javax.swing.JButton();
        sellHouseGreen3 = new javax.swing.JButton();
        sellHouseBlue1 = new javax.swing.JButton();
        sellHouseBlue2 = new javax.swing.JButton();
        mortgageBrown1 = new javax.swing.JButton();
        mortgageBrown2 = new javax.swing.JButton();
        mortgageLightBlue1 = new javax.swing.JButton();
        mortgageLightBlue2 = new javax.swing.JButton();
        mortgageLightBlue3 = new javax.swing.JButton();
        mortgagepink1 = new javax.swing.JButton();
        mortgagePink2 = new javax.swing.JButton();
        mortgagePink3 = new javax.swing.JButton();
        mortgageOrange1 = new javax.swing.JButton();
        mortgageOrange2 = new javax.swing.JButton();
        mortgageOrange3 = new javax.swing.JButton();
        mortgageRed1 = new javax.swing.JButton();
        mortgageRed2 = new javax.swing.JButton();
        mortgageRed3 = new javax.swing.JButton();
        mortgageYellow1 = new javax.swing.JButton();
        mortgageYellow2 = new javax.swing.JButton();
        mortgageYellow3 = new javax.swing.JButton();
        mortgageGreen1 = new javax.swing.JButton();
        mortgageGreen2 = new javax.swing.JButton();
        mortgageGreen3 = new javax.swing.JButton();
        mortgageBlue1 = new javax.swing.JButton();
        mortgageBlue2 = new javax.swing.JButton();
        mortgageRR = new javax.swing.JButton();
        mortgagePR = new javax.swing.JButton();
        mortgageBOR = new javax.swing.JButton();
        mortgageSL = new javax.swing.JButton();
        mortgageEC = new javax.swing.JButton();
        mortgageWW = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        unmortgageBrown1 = new javax.swing.JButton();
        unmortgageBrown2 = new javax.swing.JButton();
        unmortgageLightBlue1 = new javax.swing.JButton();
        unmortgageLightBlue2 = new javax.swing.JButton();
        unmortgageLightBlue3 = new javax.swing.JButton();
        unmortgagePink1 = new javax.swing.JButton();
        unmortgagePink2 = new javax.swing.JButton();
        unmortgagePink3 = new javax.swing.JButton();
        unmortgageOrange1 = new javax.swing.JButton();
        unmortgageOrange2 = new javax.swing.JButton();
        unmortgageOrange3 = new javax.swing.JButton();
        unmortgageRed1 = new javax.swing.JButton();
        unmortgageRed2 = new javax.swing.JButton();
        unmortgageRed3 = new javax.swing.JButton();
        unmortgageYellow1 = new javax.swing.JButton();
        unmortgageYellow2 = new javax.swing.JButton();
        unmortgageYellow3 = new javax.swing.JButton();
        unmortgageGreen1 = new javax.swing.JButton();
        unmortgageGreen2 = new javax.swing.JButton();
        unmortgageGreen3 = new javax.swing.JButton();
        unmortgageBlue1 = new javax.swing.JButton();
        unmortgageBlue2 = new javax.swing.JButton();
        unmortgageRR = new javax.swing.JButton();
        unmortgagePR = new javax.swing.JButton();
        unmortgageBOR = new javax.swing.JButton();
        unmortgageSL = new javax.swing.JButton();
        unmortgageEC = new javax.swing.JButton();
        unmortgageWW = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brown1Label.setBackground(new java.awt.Color(153, 102, 0));
        brown1Label.setText("Mediterranean Avenue:");
        brown1Label.setOpaque(true);
        jPanel1.add(brown1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        brown2Label.setBackground(new java.awt.Color(153, 102, 0));
        brown2Label.setText("Baltic Avenue:");
        brown2Label.setOpaque(true);
        jPanel1.add(brown2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        lightBlueLabel1.setBackground(new java.awt.Color(153, 204, 255));
        lightBlueLabel1.setText("Oriental Avenue:");
        lightBlueLabel1.setOpaque(true);
        jPanel1.add(lightBlueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        lightBlueLabel2.setBackground(new java.awt.Color(153, 204, 255));
        lightBlueLabel2.setText("States Avenue:");
        lightBlueLabel2.setOpaque(true);
        jPanel1.add(lightBlueLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        lightBlueLabel3.setBackground(new java.awt.Color(153, 204, 255));
        lightBlueLabel3.setText("Virginia Avenue:");
        lightBlueLabel3.setOpaque(true);
        jPanel1.add(lightBlueLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        pinkLabel1.setBackground(new java.awt.Color(255, 51, 255));
        pinkLabel1.setText("St. Charles Place:");
        pinkLabel1.setOpaque(true);
        jPanel1.add(pinkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        pinkLabel2.setBackground(new java.awt.Color(255, 51, 255));
        pinkLabel2.setText("States Avenue:");
        pinkLabel2.setOpaque(true);
        jPanel1.add(pinkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        pinkLabel3.setBackground(new java.awt.Color(255, 51, 255));
        pinkLabel3.setText("Connecticut Avenue:");
        pinkLabel3.setOpaque(true);
        jPanel1.add(pinkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        orangeLabel2.setBackground(new java.awt.Color(255, 153, 0));
        orangeLabel2.setText("Tennessee Avenue:");
        orangeLabel2.setOpaque(true);
        jPanel1.add(orangeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        orangeLabel3.setBackground(new java.awt.Color(255, 153, 0));
        orangeLabel3.setText("New York Avenue:");
        orangeLabel3.setOpaque(true);
        jPanel1.add(orangeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        orangeLabel1.setBackground(new java.awt.Color(255, 153, 0));
        orangeLabel1.setText("St. James Place:");
        orangeLabel1.setOpaque(true);
        jPanel1.add(orangeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        redLabel1.setBackground(new java.awt.Color(255, 0, 51));
        redLabel1.setText("Kentucky Avenue:");
        redLabel1.setOpaque(true);
        jPanel1.add(redLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        redLabel2.setBackground(new java.awt.Color(255, 0, 51));
        redLabel2.setText("Indiana Avenue:");
        redLabel2.setOpaque(true);
        jPanel1.add(redLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        redLabel3.setBackground(new java.awt.Color(255, 0, 51));
        redLabel3.setText("Illinois Avenue:");
        redLabel3.setOpaque(true);
        jPanel1.add(redLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 20));

        yellowLabel1.setBackground(new java.awt.Color(255, 255, 0));
        yellowLabel1.setText("Atlantic Avenue:");
        yellowLabel1.setOpaque(true);
        jPanel1.add(yellowLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        yellowLabel2.setBackground(new java.awt.Color(255, 255, 0));
        yellowLabel2.setText("Ventnor Avenue:");
        yellowLabel2.setOpaque(true);
        jPanel1.add(yellowLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        yellowLabel3.setBackground(new java.awt.Color(255, 255, 0));
        yellowLabel3.setText("Marvin Gardens:");
        yellowLabel3.setOpaque(true);
        jPanel1.add(yellowLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 20));

        greenLabel2.setBackground(new java.awt.Color(0, 153, 0));
        greenLabel2.setText("North Carolina Avenue:");
        greenLabel2.setOpaque(true);
        jPanel1.add(greenLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, 20));

        greenLabel3.setBackground(new java.awt.Color(0, 153, 0));
        greenLabel3.setText("Pennsylvania Avenue:");
        greenLabel3.setOpaque(true);
        jPanel1.add(greenLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, 20));

        greenLabel1.setBackground(new java.awt.Color(0, 153, 0));
        greenLabel1.setText("Pacific Avenue:");
        greenLabel1.setOpaque(true);
        jPanel1.add(greenLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 20));

        blueLabel1.setBackground(new java.awt.Color(0, 0, 255));
        blueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        blueLabel1.setText("Park Place:");
        blueLabel1.setOpaque(true);
        jPanel1.add(blueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, 20));

        blueLabel2.setBackground(new java.awt.Color(0, 0, 255));
        blueLabel2.setForeground(new java.awt.Color(255, 255, 255));
        blueLabel2.setText("Boardwalk:");
        blueLabel2.setOpaque(true);
        jPanel1.add(blueLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, 20));

        railroadLabel1.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel1.setText("Reading Railroad:");
        railroadLabel1.setOpaque(true);
        jPanel1.add(railroadLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, 20));

        railroadLabel2.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel2.setText("Pennsylvania Railroad:");
        railroadLabel2.setOpaque(true);
        jPanel1.add(railroadLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, 20));

        railroadLabel3.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel3.setText("B. & O. Railroad:");
        railroadLabel3.setOpaque(true);
        jPanel1.add(railroadLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, -1, 20));

        railroadLabel4.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel4.setText("Short Line");
        railroadLabel4.setOpaque(true);
        jPanel1.add(railroadLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, 20));

        railroadLabel5.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel5.setText("Electric Company:");
        railroadLabel5.setOpaque(true);
        jPanel1.add(railroadLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, -1, 20));

        railroadLabel6.setBackground(new java.awt.Color(255, 255, 255));
        railroadLabel6.setText("Water Works:");
        railroadLabel6.setOpaque(true);
        jPanel1.add(railroadLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, -1, 20));

        houseFieldBrown1.setText("0");
        jPanel1.add(houseFieldBrown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldBrown2.setText("0");
        jPanel1.add(houseFieldBrown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldLightBlue1.setText("0");
        jPanel1.add(houseFieldLightBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldLightBlue2.setText("0");
        jPanel1.add(houseFieldLightBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldLightBlue3.setText("0");
        jPanel1.add(houseFieldLightBlue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldPink1.setText("0");
        jPanel1.add(houseFieldPink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 20, 20));
        houseFieldBrown1.setEditable(false);

        houseFieldPink2.setText("0");
        jPanel1.add(houseFieldPink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldPink3.setText("0");
        jPanel1.add(houseFieldPink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldOrange1.setText("0");
        jPanel1.add(houseFieldOrange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldOrange2.setText("0");
        jPanel1.add(houseFieldOrange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldOrange3.setText("0");
        jPanel1.add(houseFieldOrange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldRed1.setText("0");
        jPanel1.add(houseFieldRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldRed2.setText("0");
        jPanel1.add(houseFieldRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldRed3.setText("0");
        jPanel1.add(houseFieldRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldYellow1.setText("0");
        jPanel1.add(houseFieldYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldYellow2.setText("0");
        jPanel1.add(houseFieldYellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldYellow3.setText("0");
        jPanel1.add(houseFieldYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldGreen1.setText("0");
        jPanel1.add(houseFieldGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldGreen2.setText("0");
        jPanel1.add(houseFieldGreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldGreen3.setText("0");
        jPanel1.add(houseFieldGreen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldBlue1.setText("0");
        jPanel1.add(houseFieldBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 20, -1));
        houseFieldBrown1.setEditable(false);

        houseFieldBlue2.setText("0");
        jPanel1.add(houseFieldBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 20, -1));
        houseFieldBrown1.setEditable(false);

        buyHouseBrown1.setText("Buy House");
        jPanel1.add(buyHouseBrown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        buyHouseBrown2.setText("Buy House");
        jPanel1.add(buyHouseBrown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        buyHouseLightBlue1.setText("Buy House");
        jPanel1.add(buyHouseLightBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        buyHouseLightBlue2.setText("Buy House");
        jPanel1.add(buyHouseLightBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        buyHouseLightBlue3.setText("Buy House");
        jPanel1.add(buyHouseLightBlue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        buyHousePink1.setText("Buy House");
        jPanel1.add(buyHousePink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        buyHousePink2.setText("Buy House");
        jPanel1.add(buyHousePink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buyHousePink3.setText("Buy House");
        jPanel1.add(buyHousePink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        buyHouseOrange1.setText("Buy House");
        jPanel1.add(buyHouseOrange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        buyHouseOrange2.setText("Buy House");
        jPanel1.add(buyHouseOrange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        buyHouseOrange3.setText("Buy House");
        jPanel1.add(buyHouseOrange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        buyHouseRed1.setText("Buy House");
        jPanel1.add(buyHouseRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        buyHouseRed2.setText("Buy House");
        jPanel1.add(buyHouseRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        buyHouseRed3.setText("Buy House");
        jPanel1.add(buyHouseRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        buyHouseYellow1.setText("Buy House");
        jPanel1.add(buyHouseYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        buyHouseYellow2.setText("Buy House");
        jPanel1.add(buyHouseYellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        buyHouseYellow3.setText("Buy House");
        jPanel1.add(buyHouseYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        buyHouseGreen1.setText("Buy House");
        jPanel1.add(buyHouseGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        buyHouseGreen2.setText("Buy House");
        jPanel1.add(buyHouseGreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));

        buyHouseGreen3.setText("Buy House");
        jPanel1.add(buyHouseGreen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        buyHouseBlue1.setText("Buy House");
        jPanel1.add(buyHouseBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, -1, -1));

        buyHouseBlue2.setText("Buy House");
        jPanel1.add(buyHouseBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, -1, -1));

        sellHouseBrown1.setText("Sell House");
        jPanel1.add(sellHouseBrown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        sellHouseBrown2.setText("Sell House");
        jPanel1.add(sellHouseBrown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        sellHouseLightBlue1.setText("Sell House");
        jPanel1.add(sellHouseLightBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        sellHouseLightBlue2.setText("Sell House");
        jPanel1.add(sellHouseLightBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        sellHouseLightBlue3.setText("Sell House");
        jPanel1.add(sellHouseLightBlue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        sellHousePink1.setText("Sell House");
        jPanel1.add(sellHousePink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        sellHousePink2.setText("Sell House");
        jPanel1.add(sellHousePink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        sellHousePink3.setText("Sell House");
        jPanel1.add(sellHousePink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        sellHouseOrange1.setText("Sell House");
        jPanel1.add(sellHouseOrange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        sellHouseOrange2.setText("Sell House");
        jPanel1.add(sellHouseOrange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        sellHouseOrange3.setText("Sell House");
        jPanel1.add(sellHouseOrange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        sellHouseRed1.setText("Sell House");
        jPanel1.add(sellHouseRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        sellHouseRed2.setText("Sell House");
        jPanel1.add(sellHouseRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        sellHouseRed3.setText("Sell House");
        jPanel1.add(sellHouseRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        sellHouseYellow1.setText("Sell House");
        jPanel1.add(sellHouseYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        sellHouseYellow2.setText("Sell House");
        jPanel1.add(sellHouseYellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        sellHouseYellow3.setText("Sell House");
        jPanel1.add(sellHouseYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        sellHouseGreen1.setText("Sell House");
        jPanel1.add(sellHouseGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        sellHouseGreen2.setText("Sell House");
        jPanel1.add(sellHouseGreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        sellHouseGreen3.setText("Sell House");
        jPanel1.add(sellHouseGreen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, -1));

        sellHouseBlue1.setText("Sell House");
        jPanel1.add(sellHouseBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, -1, -1));

        sellHouseBlue2.setText("Sell House");
        jPanel1.add(sellHouseBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, -1, -1));

        mortgageBrown1.setText("Mortgage");
        jPanel1.add(mortgageBrown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, -1));

        mortgageBrown2.setText("Mortgage");
        jPanel1.add(mortgageBrown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, -1));

        mortgageLightBlue1.setText("Mortgage");
        jPanel1.add(mortgageLightBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, -1));

        mortgageLightBlue2.setText("Mortgage");
        jPanel1.add(mortgageLightBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 100, -1));

        mortgageLightBlue3.setText("Mortgage");
        jPanel1.add(mortgageLightBlue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, -1));

        mortgagepink1.setText("Mortgage");
        jPanel1.add(mortgagepink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 100, -1));

        mortgagePink2.setText("Mortgage");
        jPanel1.add(mortgagePink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, -1));

        mortgagePink3.setText("Mortgage");
        jPanel1.add(mortgagePink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, -1));

        mortgageOrange1.setText("Mortgage");
        jPanel1.add(mortgageOrange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, -1));

        mortgageOrange2.setText("Mortgage");
        jPanel1.add(mortgageOrange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 100, -1));

        mortgageOrange3.setText("Mortgage");
        jPanel1.add(mortgageOrange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, -1));

        mortgageRed1.setText("Mortgage");
        jPanel1.add(mortgageRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 100, -1));

        mortgageRed2.setText("Mortgage");
        jPanel1.add(mortgageRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 100, -1));

        mortgageRed3.setText("Mortgage");
        jPanel1.add(mortgageRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 100, -1));

        mortgageYellow1.setText("Mortgage");
        jPanel1.add(mortgageYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 100, -1));

        mortgageYellow2.setText("Mortgage");
        jPanel1.add(mortgageYellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 100, -1));

        mortgageYellow3.setText("Mortgage");
        jPanel1.add(mortgageYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 100, -1));

        mortgageGreen1.setText("Mortgage");
        jPanel1.add(mortgageGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 100, -1));

        mortgageGreen2.setText("Mortgage");
        jPanel1.add(mortgageGreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 100, -1));

        mortgageGreen3.setText("Mortgage");
        jPanel1.add(mortgageGreen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 100, -1));

        mortgageBlue1.setText("Mortgage");
        jPanel1.add(mortgageBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 100, -1));

        mortgageBlue2.setText("Mortgage");
        jPanel1.add(mortgageBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 100, -1));

        mortgageRR.setText("Mortgage");
        jPanel1.add(mortgageRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 100, -1));

        mortgagePR.setText("Mortgage");
        jPanel1.add(mortgagePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 710, 100, -1));

        mortgageBOR.setText("Mortgage");
        jPanel1.add(mortgageBOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 100, -1));

        mortgageSL.setText("Mortgage");
        jPanel1.add(mortgageSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 770, 100, -1));

        mortgageEC.setText("Mortgage");
        jPanel1.add(mortgageEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 800, 100, -1));

        mortgageWW.setText("Mortgage");
        jPanel1.add(mortgageWW, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 830, 100, -1));

        closeButton.setText("Close Menu");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 840, -1, -1));

        unmortgageBrown1.setText("Unmortgage");
        jPanel1.add(unmortgageBrown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 100, -1));

        unmortgageBrown2.setText("Unmortgage");
        jPanel1.add(unmortgageBrown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, -1));

        unmortgageLightBlue1.setText("Unmortgage");
        jPanel1.add(unmortgageLightBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 100, -1));

        unmortgageLightBlue2.setText("Unmortgage");
        jPanel1.add(unmortgageLightBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 100, -1));

        unmortgageLightBlue3.setText("Unmortgage");
        jPanel1.add(unmortgageLightBlue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 100, -1));

        unmortgagePink1.setText("Unmortgage");
        jPanel1.add(unmortgagePink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 100, -1));

        unmortgagePink2.setText("Unmortgage");
        jPanel1.add(unmortgagePink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 100, -1));

        unmortgagePink3.setText("Unmortgage");
        jPanel1.add(unmortgagePink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 100, -1));

        unmortgageOrange1.setText("Unmortgage");
        jPanel1.add(unmortgageOrange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 100, -1));

        unmortgageOrange2.setText("Unmortgage");
        jPanel1.add(unmortgageOrange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 100, -1));

        unmortgageOrange3.setText("Unmortgage");
        jPanel1.add(unmortgageOrange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 100, -1));

        unmortgageRed1.setText("Unmortgage");
        jPanel1.add(unmortgageRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, -1));

        unmortgageRed2.setText("Unmortgage");
        jPanel1.add(unmortgageRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 100, -1));

        unmortgageRed3.setText("Unmortgage");
        jPanel1.add(unmortgageRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 100, -1));

        unmortgageYellow1.setText("Unmortgage");
        jPanel1.add(unmortgageYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 100, -1));

        unmortgageYellow2.setText("Unmortgage");
        jPanel1.add(unmortgageYellow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 100, -1));

        unmortgageYellow3.setText("Unmortgage");
        jPanel1.add(unmortgageYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 100, -1));

        unmortgageGreen1.setText("Unmortgage");
        jPanel1.add(unmortgageGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 100, -1));

        unmortgageGreen2.setText("Unmortgage");
        jPanel1.add(unmortgageGreen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 100, -1));

        unmortgageGreen3.setText("Unmortgage");
        jPanel1.add(unmortgageGreen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 100, -1));

        unmortgageBlue1.setText("Unmortgage");
        jPanel1.add(unmortgageBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 100, -1));

        unmortgageBlue2.setText("Unmortgage");
        jPanel1.add(unmortgageBlue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, 100, -1));

        unmortgageRR.setText("Unmortgage");
        jPanel1.add(unmortgageRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, 100, -1));

        unmortgagePR.setText("Unmortgage");
        jPanel1.add(unmortgagePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 710, 100, -1));

        unmortgageBOR.setText("Unmortgage");
        jPanel1.add(unmortgageBOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 740, 100, -1));

        unmortgageSL.setText("Unmortgage");
        jPanel1.add(unmortgageSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, 100, -1));

        unmortgageEC.setText("Unmortgage");
        jPanel1.add(unmortgageEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 800, 100, -1));

        unmortgageWW.setText("Unmortgage");
        jPanel1.add(unmortgageWW, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 830, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player1ManagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player1ManagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player1ManagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player1ManagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Player1ManagePage dialog = new Player1ManagePage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel blueLabel1;
    private javax.swing.JLabel blueLabel2;
    private javax.swing.JLabel brown1Label;
    private javax.swing.JLabel brown2Label;
    private javax.swing.JButton buyHouseBlue1;
    private javax.swing.JButton buyHouseBlue2;
    private javax.swing.JButton buyHouseBrown1;
    private javax.swing.JButton buyHouseBrown2;
    private javax.swing.JButton buyHouseGreen1;
    private javax.swing.JButton buyHouseGreen2;
    private javax.swing.JButton buyHouseGreen3;
    private javax.swing.JButton buyHouseLightBlue1;
    private javax.swing.JButton buyHouseLightBlue2;
    private javax.swing.JButton buyHouseLightBlue3;
    private javax.swing.JButton buyHouseOrange1;
    private javax.swing.JButton buyHouseOrange2;
    private javax.swing.JButton buyHouseOrange3;
    private javax.swing.JButton buyHousePink1;
    private javax.swing.JButton buyHousePink2;
    private javax.swing.JButton buyHousePink3;
    private javax.swing.JButton buyHouseRed1;
    private javax.swing.JButton buyHouseRed2;
    private javax.swing.JButton buyHouseRed3;
    private javax.swing.JButton buyHouseYellow1;
    private javax.swing.JButton buyHouseYellow2;
    private javax.swing.JButton buyHouseYellow3;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel greenLabel1;
    private javax.swing.JLabel greenLabel2;
    private javax.swing.JLabel greenLabel3;
    private javax.swing.JTextField houseFieldBlue1;
    private javax.swing.JTextField houseFieldBlue2;
    private javax.swing.JTextField houseFieldBrown1;
    private javax.swing.JTextField houseFieldBrown2;
    private javax.swing.JTextField houseFieldGreen1;
    private javax.swing.JTextField houseFieldGreen2;
    private javax.swing.JTextField houseFieldGreen3;
    private javax.swing.JTextField houseFieldLightBlue1;
    private javax.swing.JTextField houseFieldLightBlue2;
    private javax.swing.JTextField houseFieldLightBlue3;
    private javax.swing.JTextField houseFieldOrange1;
    private javax.swing.JTextField houseFieldOrange2;
    private javax.swing.JTextField houseFieldOrange3;
    private javax.swing.JTextField houseFieldPink1;
    private javax.swing.JTextField houseFieldPink2;
    private javax.swing.JTextField houseFieldPink3;
    private javax.swing.JTextField houseFieldRed1;
    private javax.swing.JTextField houseFieldRed2;
    private javax.swing.JTextField houseFieldRed3;
    private javax.swing.JTextField houseFieldYellow1;
    private javax.swing.JTextField houseFieldYellow2;
    private javax.swing.JTextField houseFieldYellow3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lightBlueLabel1;
    private javax.swing.JLabel lightBlueLabel2;
    private javax.swing.JLabel lightBlueLabel3;
    private javax.swing.JButton mortgageBOR;
    private javax.swing.JButton mortgageBlue1;
    private javax.swing.JButton mortgageBlue2;
    private javax.swing.JButton mortgageBrown1;
    private javax.swing.JButton mortgageBrown2;
    private javax.swing.JButton mortgageEC;
    private javax.swing.JButton mortgageGreen1;
    private javax.swing.JButton mortgageGreen2;
    private javax.swing.JButton mortgageGreen3;
    private javax.swing.JButton mortgageLightBlue1;
    private javax.swing.JButton mortgageLightBlue2;
    private javax.swing.JButton mortgageLightBlue3;
    private javax.swing.JButton mortgageOrange1;
    private javax.swing.JButton mortgageOrange2;
    private javax.swing.JButton mortgageOrange3;
    private javax.swing.JButton mortgagePR;
    private javax.swing.JButton mortgagePink2;
    private javax.swing.JButton mortgagePink3;
    private javax.swing.JButton mortgageRR;
    private javax.swing.JButton mortgageRed1;
    private javax.swing.JButton mortgageRed2;
    private javax.swing.JButton mortgageRed3;
    private javax.swing.JButton mortgageSL;
    private javax.swing.JButton mortgageWW;
    private javax.swing.JButton mortgageYellow1;
    private javax.swing.JButton mortgageYellow2;
    private javax.swing.JButton mortgageYellow3;
    private javax.swing.JButton mortgagepink1;
    private javax.swing.JLabel orangeLabel1;
    private javax.swing.JLabel orangeLabel2;
    private javax.swing.JLabel orangeLabel3;
    private javax.swing.JLabel pinkLabel1;
    private javax.swing.JLabel pinkLabel2;
    private javax.swing.JLabel pinkLabel3;
    private javax.swing.JLabel railroadLabel1;
    private javax.swing.JLabel railroadLabel2;
    private javax.swing.JLabel railroadLabel3;
    private javax.swing.JLabel railroadLabel4;
    private javax.swing.JLabel railroadLabel5;
    private javax.swing.JLabel railroadLabel6;
    private javax.swing.JLabel redLabel1;
    private javax.swing.JLabel redLabel2;
    private javax.swing.JLabel redLabel3;
    private javax.swing.JButton sellHouseBlue1;
    private javax.swing.JButton sellHouseBlue2;
    private javax.swing.JButton sellHouseBrown1;
    private javax.swing.JButton sellHouseBrown2;
    private javax.swing.JButton sellHouseGreen1;
    private javax.swing.JButton sellHouseGreen2;
    private javax.swing.JButton sellHouseGreen3;
    private javax.swing.JButton sellHouseLightBlue1;
    private javax.swing.JButton sellHouseLightBlue2;
    private javax.swing.JButton sellHouseLightBlue3;
    private javax.swing.JButton sellHouseOrange1;
    private javax.swing.JButton sellHouseOrange2;
    private javax.swing.JButton sellHouseOrange3;
    private javax.swing.JButton sellHousePink1;
    private javax.swing.JButton sellHousePink2;
    private javax.swing.JButton sellHousePink3;
    private javax.swing.JButton sellHouseRed1;
    private javax.swing.JButton sellHouseRed2;
    private javax.swing.JButton sellHouseRed3;
    private javax.swing.JButton sellHouseYellow1;
    private javax.swing.JButton sellHouseYellow2;
    private javax.swing.JButton sellHouseYellow3;
    private javax.swing.JButton unmortgageBOR;
    private javax.swing.JButton unmortgageBlue1;
    private javax.swing.JButton unmortgageBlue2;
    private javax.swing.JButton unmortgageBrown1;
    private javax.swing.JButton unmortgageBrown2;
    private javax.swing.JButton unmortgageEC;
    private javax.swing.JButton unmortgageGreen1;
    private javax.swing.JButton unmortgageGreen2;
    private javax.swing.JButton unmortgageGreen3;
    private javax.swing.JButton unmortgageLightBlue1;
    private javax.swing.JButton unmortgageLightBlue2;
    private javax.swing.JButton unmortgageLightBlue3;
    private javax.swing.JButton unmortgageOrange1;
    private javax.swing.JButton unmortgageOrange2;
    private javax.swing.JButton unmortgageOrange3;
    private javax.swing.JButton unmortgagePR;
    private javax.swing.JButton unmortgagePink1;
    private javax.swing.JButton unmortgagePink2;
    private javax.swing.JButton unmortgagePink3;
    private javax.swing.JButton unmortgageRR;
    private javax.swing.JButton unmortgageRed1;
    private javax.swing.JButton unmortgageRed2;
    private javax.swing.JButton unmortgageRed3;
    private javax.swing.JButton unmortgageSL;
    private javax.swing.JButton unmortgageWW;
    private javax.swing.JButton unmortgageYellow1;
    private javax.swing.JButton unmortgageYellow2;
    private javax.swing.JButton unmortgageYellow3;
    private javax.swing.JLabel yellowLabel1;
    private javax.swing.JLabel yellowLabel2;
    private javax.swing.JLabel yellowLabel3;
    // End of variables declaration//GEN-END:variables
}
